package jason.ui;

import java.util.List;
import java.util.Scanner;
import java.util.function.Consumer;

import jason.task.Task;
import jason.task.TaskList;

/**
 * Handles all interaction between Jason and the command-line user.
 */
public class Ui {
    public static final String START_MESSAGE = "Hello! My name is Jason, inspired by JSON files "
            + "used by software engineers.";
    public static final String HELP_MESSAGE = "How may I help you today?";
    public static final String END_MESSAGE = "Goodbye! Hope to see you again.";
    private static final String DIVIDER = "_______";
    private static final String NO_MATCHING_TASKS_MESSAGE = "No matching tasks found.";
    private static final String MATCHING_TASKS_HEADER = "Here are the matching tasks in your list:";
    private static final String ADDED_TASK_PREFIX = "Added: ";
    private static final String MARKED_COMPLETE_MESSAGE = "Nice! I have marked this task as done:";
    private static final String MARKED_INCOMPLETE_MESSAGE = "OK, I've marked this task as not done yet:";
    private static final String DELETED_TASK_MESSAGE = "Alright. I will remove this task:";
    private static final String TASK_COUNT_MESSAGE = "You have %d tasks left in your list";

    private final Scanner scanner;
    private final Consumer<String> output;

    /**
     * Creates a UI connected to standard input and output.
     */
    public Ui() {
        this.scanner = new Scanner(System.in);
        this.output = System.out::println;
    }

    /**
     * Creates a UI that sends each output line to the supplied consumer.
     *
     * @param output destination for messages generated by the UI.
     */
    public Ui(Consumer<String> output) {
        if (output == null) {
            throw new IllegalArgumentException("The output consumer cannot be null.");
        }
        this.scanner = new Scanner(System.in);
        this.output = output;
    }

    /**
     * Prints the chatbot's welcome messages.
     */
    public void showWelcome() {
        output.accept(START_MESSAGE);
        output.accept(HELP_MESSAGE);
    }

    /**
     * Reads the next command entered by the user.
     *
     * @return next command entered by the user.
     */
    public String readCommand() {
        return scanner.nextLine();
    }

    /**
     * Prints the chatbot's goodbye message.
     */
    public void showGoodbye() {
        output.accept(END_MESSAGE);
    }

    /**
     * Prints the divider between command-line interactions.
     */
    public void showLine() {
        output.accept(DIVIDER);
    }

    /**
     * Prints an error message.
     *
     * @param exception exception whose message should be shown.
     */
    public void showError(Exception exception) {
        output.accept(exception.toString());
    }

    /**
     * Displays the current task list.
     *
     * @param taskList task list to display.
     */
    public void showTaskList(TaskList taskList) {
        output.accept(taskList.toString());
    }

    /**
     * Displays tasks matching a search keyword.
     *
     * @param matchingTasks tasks that matched the user's search.
     */
    public void showMatchingTasks(List<Task> matchingTasks) {
        if (matchingTasks.isEmpty()) {
            output.accept(NO_MATCHING_TASKS_MESSAGE);
            return;
        }

        output.accept(MATCHING_TASKS_HEADER);
        for (int i = 0; i < matchingTasks.size(); i++) {
            output.accept(String.format("%d. %s", i + 1, matchingTasks.get(i)));
        }
    }

    /**
     * Displays a newly added task.
     *
     * @param task task that was added.
     */
    public void showAddedTask(Task task) {
        output.accept(ADDED_TASK_PREFIX + task);
    }

    /**
     * Displays a completed task confirmation.
     *
     * @param task task that was marked complete.
     */
    public void showMarkedComplete(Task task) {
        output.accept(MARKED_COMPLETE_MESSAGE);
        output.accept(task.toString());
    }

    /**
     * Displays an incomplete task confirmation.
     *
     * @param task task that was marked incomplete.
     */
    public void showMarkedIncomplete(Task task) {
        output.accept(MARKED_INCOMPLETE_MESSAGE);
        output.accept(task.toString());
    }

    /**
     * Displays a task deletion confirmation and the remaining task count.
     *
     * @param task task that was deleted.
     * @param remainingTasks number of tasks left after deletion.
     */
    public void showDeletedTask(Task task, int remainingTasks) {
        output.accept(DELETED_TASK_MESSAGE);
        output.accept(task.toString());
        output.accept(String.format(TASK_COUNT_MESSAGE, remainingTasks));
    }
}
