package jason.ui;

import java.util.List;
import java.util.Scanner;
import java.util.function.Consumer;

import jason.Jason;
import jason.task.Task;
import jason.task.TaskList;

/**
 * Handles all interaction between Jason and the command-line user.
 */
public class Ui {
    private final Scanner scanner;
    private final Consumer<String> output;

    /**
     * Creates a UI connected to standard input and output.
     */
    public Ui() {
        this.scanner = new Scanner(System.in);
        this.output = System.out::println;
    }

    /**
     * Creates a UI that sends each output line to the supplied consumer.
     *
     * @param output destination for messages generated by the UI.
     */
    public Ui(Consumer<String> output) {
        if (output == null) {
            throw new IllegalArgumentException("The output consumer cannot be null.");
        }
        this.scanner = new Scanner(System.in);
        this.output = output;
    }

    /**
     * Prints the chatbot's welcome messages.
     */
    public void showWelcome() {
        output.accept(Jason.START_MESSAGE);
        output.accept(Jason.HELP_MESSAGE);
    }

    /**
     * Reads the next command entered by the user.
     *
     * @return next command entered by the user.
     */
    public String readCommand() {
        return scanner.nextLine();
    }

    /**
     * Prints the chatbot's goodbye message.
     */
    public void showGoodbye() {
        output.accept(Jason.END_MESSAGE);
    }

    /**
     * Prints the divider between command-line interactions.
     */
    public void showLine() {
        output.accept("_______");
    }

    /**
     * Prints an error message.
     *
     * @param exception exception whose message should be shown.
     */
    public void showError(Exception exception) {
        output.accept(exception.toString());
    }

    /**
     * Displays the current task list.
     *
     * @param taskList task list to display.
     */
    public void showTaskList(TaskList taskList) {
        output.accept(taskList.toString());
    }

    /**
     * Displays tasks matching a search keyword.
     *
     * @param matchingTasks tasks that matched the user's search.
     */
    public void showMatchingTasks(List<Task> matchingTasks) {
        if (matchingTasks.isEmpty()) {
            output.accept("No matching tasks found.");
            return;
        }

        output.accept("Here are the matching tasks in your list:");
        for (int i = 0; i < matchingTasks.size(); i++) {
            output.accept(String.format("%d. %s", i + 1, matchingTasks.get(i)));
        }
    }

    /**
     * Displays a newly added task.
     *
     * @param task task that was added.
     */
    public void showAddedTask(Task task) {
        output.accept("Added: " + task);
    }

    /**
     * Displays a completed task confirmation.
     *
     * @param task task that was marked complete.
     */
    public void showMarkedComplete(Task task) {
        output.accept("Nice! I have marked this task as done:");
        output.accept(task.toString());
    }

    /**
     * Displays an incomplete task confirmation.
     *
     * @param task task that was marked incomplete.
     */
    public void showMarkedIncomplete(Task task) {
        output.accept("OK, I've marked this task as not done yet:");
        output.accept(task.toString());
    }

    /**
     * Displays a task deletion confirmation and the remaining task count.
     *
     * @param task task that was deleted.
     * @param remainingTasks number of tasks left after deletion.
     */
    public void showDeletedTask(Task task, int remainingTasks) {
        output.accept("Alright. I will remove this task:");
        output.accept(task.toString());
        output.accept(String.format("You have %d tasks left in your list", remainingTasks));
    }
}
