package jason;

import jason.command.Command;
import jason.exception.InvalidIndexException;
import jason.storage.Storage;
import jason.task.Task;
import jason.task.TaskList;
import jason.ui.Ui;

/**
 * Coordinates the user interface, command execution, task list, and storage.
 */
public class Jason {
    public static final String START_MESSAGE = "Hello! My name is Jason, inspired by JSON files "
            + "used by software engineers.";
    public static final String HELP_MESSAGE = "How may I help you today?";
    public static final String END_MESSAGE = "Goodbye! Hope to see you again.";
    private static final String SAVE_FILE = "./data/jason.txt";
    private final Storage storage;
    private final Ui ui;
    private final Parser parser;
    private TaskList taskList;

    /**
     * Creates Jason with the default command-line UI.
     */
    public Jason() {
        this(new Ui());
    }

    /**
     * Creates Jason with the UI used by its application loop.
     *
     * @param ui user interface used to interact with the user.
     */
    public Jason(Ui ui) {
        if (ui == null) {
            throw new IllegalArgumentException("The UI cannot be null.");
        }
        this.storage = new Storage(SAVE_FILE);
        this.taskList = new TaskList(storage.load());
        this.ui = ui;
        this.parser = new Parser();
    }

    /**
     * Adds a task and persists the updated task list.
     *
     * @param t task to add.
     * @throws IllegalArgumentException if the task is null.
     */
    public void addTask(Task t) {
        if (t == null) {
            throw new IllegalArgumentException("A task cannot be null.");
        }
        this.taskList.add(t);
        saveTasks();
    }

    /**
     * Returns the task at a one-based list index.
     *
     * @param i one-based index of the task.
     * @return task at the specified index.
     */
    public Task getTask(int i) {
        return this.taskList.get(i);
    }

    /**
     * Returns the number of tasks currently stored.
     *
     * @return number of stored tasks.
     */
    public int size() {
        return this.taskList.size();
    }

    /**
     * Returns the task list managed by Jason.
     *
     * @return Jason's task list.
     */
    public TaskList getTaskList() {
        return this.taskList;
    }

    /**
     * Processes one command and returns the response for a graphical user interface.
     *
     * @param input command entered by the user.
     * @return response generated by the command, without trailing whitespace.
     */
    public String getResponse(String input) {
        StringBuilder response = new StringBuilder();
        Ui responseUi = new Ui(message -> response.append(message).append(System.lineSeparator()));
        try {
            Command command = parser.parse(input);
            command.execute(taskList, responseUi, storage);
        } catch (Exception exception) {
            responseUi.showError(exception);
        }
        return response.toString().stripTrailing();
    }

    /**
     * Marks the task at a one-based index complete and persists the change.
     *
     * @param i one-based index of the task.
     * @throws InvalidIndexException if the index does not identify a task.
     */
    public void markTaskAsComplete(int i) throws InvalidIndexException {
        if (!taskList.isValidIndex(i)) {
            throw new InvalidIndexException();
        }
        this.getTask(i).markComplete();
        saveTasks();
    }

    /**
     * Marks the task at a one-based index incomplete and persists the change.
     *
     * @param i one-based index of the task.
     * @throws InvalidIndexException if the index does not identify a task.
     */
    public void markTaskAsIncomplete(int i) throws InvalidIndexException {
        if (!taskList.isValidIndex(i)) {
            throw new InvalidIndexException();
        }
        this.getTask(i).markIncomplete();
        saveTasks();
    }

    /**
     * Deletes the task at a one-based index and persists the change.
     *
     * @param i one-based index of the task.
     * @throws InvalidIndexException if the index does not identify a task.
     */
    public void deleteTask(int i) throws InvalidIndexException {
        if (!taskList.isValidIndex(i)) {
            throw new InvalidIndexException();
        }
        this.taskList.remove(i);
        saveTasks();
    }

    /**
     * Writes the current task list to disk after a successful list mutation.
     * The parent directory is created automatically the first time the file is saved.
     */
    private void saveTasks() {
        storage.save(taskList);
    }

    /**
     * Runs the command-line application until the user enters {@code bye}.
     */
    public void run() {
        ui.showWelcome();
        boolean isExit = false;

        while (!isExit) {
            try {
                String fullCommand = ui.readCommand();
                ui.showLine();
                Command command = parser.parse(fullCommand);
                command.execute(taskList, ui, storage);
                isExit = command.isExit();
            } catch (Exception e) {
                ui.showError(e);
            } finally {
                ui.showLine();
            }
        }

        ui.showGoodbye();
    }
}
